# Generated by Django 5.0.7 on 2024-07-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookusers',
            name='email',
            field=models.CharField(db_index=True, max_length=250, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='facebookusers',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Пароль'),
        ),
    ]
