# Generated by Django 5.0.7 on 2024-07-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_users', '0002_alter_facebookusers_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookusers',
            name='is_register_fb',
            field=models.BooleanField(default=False, verbose_name='Прошел регистрацию на Fb'),
        ),
    ]
