# Generated by Django 5.0.7 on 2024-07-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_users', '0004_genderusers_facebookusers_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookusers',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='user_fb/', verbose_name='Изображение'),
        ),
    ]
